spring:
  data:
    mongodb:
      uri: mongodb://localhost/:27017
      database: Test
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  h2:
    console:
      enabled: true
