name: Gradle Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2

      - run: cd spring-batch-mongo
      - run: ls
      - run: gradle build pitest

      - uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: mongo-batch-mongo/build/reports

  test-with-mongo-versions:
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo: [ "4.0", "4.2", "4.4" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2

      - run: cd spring-batch-mongo
      - run: gradle test -Dmongo=${{ matrix.mongo }}

      - uses: actions/upload-artifact@v2
        with:
          name: test-with-mongo-${{ matrix.mongo }}
          path: mongo-batch-mongo/build/reports/tests/test
