name: Gradle Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup mongodb 1
        run: docker run -d -p 27017:27017 --name mongoSvr mongo:${{ matrix.mongo }} mongod --replSet rs0 --port 27017
      - name: setup mongodb 2
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          retry_wait_seconds: 2
          command: docker exec -i mongoSvr mongo --eval "rs.initiate()"
      - name: if failed, get mongo logs
        run: docker logs mongoSvr
        if: failure()

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: build

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build-reports
          path: |
            build/reports
            **/build/reports
