name: Publish to OSSRH Package Registry

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - run: gradle publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_SIGNINGKEY: ${{ secrets.SIGNING_SIGNINGKEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}