name: Test

on: [ pull_request, workflow_dispatch ]

jobs:
  mongo-version-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo: [ "4.0", "4.2", "4.4", "5.0" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - run: gradle test -Dmongo=${{ matrix.mongo }}

      - uses: actions/upload-artifact@v2
        with:
          name: test-with-mongo-${{ matrix.mongo }}
          path: mongo-batch-mongo/build/reports/tests/test

  pitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: pitest

      - uses: actions/upload-artifact@v2
        with:
          name: pitest
          path: mongo-batch-mongo/build/reports